[tool]
[tool.poetry]
authors = ["Your Name <you@example.com>"]
name = "root"
version = "0.0.0"
description = "Anybadge demo"
[tool.poetry.dependencies]
anybadge = "==1.7.0"
flask = "==1.0.2"
python = "^3.7"
